steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/fluted-bot-385510/module-registry', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/fluted-bot-385510/module-registry']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['compute', 'instances', 'create-with-container', 'module-registry-instance','--zone','us-central1-a',  '--container-image',  'gcr.io/fluted-bot-385510/module-registry/cloud-run-source-deploy', '--metadata', 'google-logging-enabled=true']
   